import { BookOpen } from 'lucide-react'
import { formatIdr } from '../../../lib/format'
import { Field, Select } from '../../../components/ui/Form'
import { BOOK_PRESETS, PAPER_PRESETS } from '../paperCalculatorDefaults'
import { CalculatorField } from '../components/CalculatorField'
import { CustomSizeControls } from '../components/CustomSizeControls'
import { PresetButtons } from '../components/PresetButtons'
import { ResultMetric } from '../components/ResultMetric'
import { ValidationSummary, WarningList } from '../components/ValidationSummary'
import { formatDecimal } from '../domain/numbers'

export function BookCalculatorPanel({ draft, onChange, onDeleteSize, onSaveSize, result, sizes }) {
  const update = (field, value) => onChange({ ...draft, [field]: value })
  const data = result.data ?? {}
  return (
    <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
      <section className="rounded-4xl border border-white/80 bg-white p-6 shadow-xl shadow-slate-300/40">
        <div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-50 text-blue-600"><BookOpen size={20} /></span><div><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">Produksi buku</p><h2 className="text-xl font-black tracking-tight text-slate-950">Kalkulator Buku</h2></div></div>
        <div className="mt-6 space-y-6">
          <PresetButtons label="Kertas cetak" onSelect={(preset) => onChange({ ...draft, paperWidth: preset.width, paperHeight: preset.height })} presets={[...PAPER_PRESETS.slice(0, 3), ...sizes.filter((size) => size.type === 'paper')]} selectedHeight={draft.paperHeight} selectedWidth={draft.paperWidth} />
          <div className="grid gap-4 sm:grid-cols-2"><CalculatorField label="Lebar kertas" onChange={(event) => update('paperWidth', event.target.value)} unit="cm" value={draft.paperWidth} /><CalculatorField label="Tinggi kertas" onChange={(event) => update('paperHeight', event.target.value)} unit="cm" value={draft.paperHeight} /></div>
          <CustomSizeControls currentHeight={draft.paperHeight} currentWidth={draft.paperWidth} onApply={(size) => onChange({ ...draft, paperWidth: String(size.width), paperHeight: String(size.height) })} onDelete={onDeleteSize} onSave={onSaveSize} sizes={sizes} type="paper" />
          <div className="border-t border-slate-100 pt-6"><PresetButtons label="Ukuran buku jadi" onSelect={(preset) => onChange({ ...draft, bookWidth: preset.width, bookHeight: preset.height })} presets={[...BOOK_PRESETS, ...sizes.filter((size) => size.type === 'book')]} selectedHeight={draft.bookHeight} selectedWidth={draft.bookWidth} /><div className="mt-4 grid gap-4 sm:grid-cols-2"><CalculatorField label="Lebar buku" onChange={(event) => update('bookWidth', event.target.value)} unit="cm" value={draft.bookWidth} /><CalculatorField label="Tinggi buku" onChange={(event) => update('bookHeight', event.target.value)} unit="cm" value={draft.bookHeight} /></div><div className="mt-4"><CustomSizeControls currentHeight={draft.bookHeight} currentWidth={draft.bookWidth} onApply={(size) => onChange({ ...draft, bookWidth: String(size.width), bookHeight: String(size.height) })} onDelete={onDeleteSize} onSave={onSaveSize} sizes={sizes} type="book" /></div></div>
          <div className="border-t border-slate-100 pt-6"><h3 className="text-sm font-black text-slate-900">Detail cetak</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><CalculatorField label="Jumlah halaman" onChange={(event) => update('pages', event.target.value)} unit="halaman" value={draft.pages} /><CalculatorField label="Jumlah eksemplar" onChange={(event) => update('copies', event.target.value)} unit="buku" value={draft.copies} /><Field label="Mode cetak"><Select aria-label="Mode cetak" onChange={(event) => update('printMode', event.target.value)} value={draft.printMode}><option value="duplex">Bolak-balik / duplex</option><option value="simplex">Satu sisi / simplex</option></Select></Field><Field label="Jenis jilid"><Select aria-label="Jenis jilid" onChange={(event) => update('binding', event.target.value)} value={draft.binding}><option value="perfect">Perfect binding</option><option value="saddle">Saddle stitch</option><option value="spiral">Spiral / ring</option></Select></Field><Field label="Jenis cover"><Select aria-label="Jenis cover" onChange={(event) => update('coverType', event.target.value)} value={draft.coverType}><option value="soft">Soft cover</option><option value="hard">Hard cover</option><option value="none">Tanpa cover terpisah</option></Select></Field><CalculatorField disabled={draft.coverType === 'none'} label="Tebal punggung" onChange={(event) => update('spineThickness', event.target.value)} unit="cm" value={draft.spineThickness} /></div></div>
          <div className="border-t border-slate-100 pt-6"><h3 className="text-sm font-black text-slate-900">Harga kertas</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><CalculatorField label="Harga rim isi" onChange={(event) => update('contentPricePerRim', event.target.value)} unit="Rp" value={draft.contentPricePerRim} /><CalculatorField disabled={draft.coverType === 'none'} label="Harga rim cover" onChange={(event) => update('coverPricePerRim', event.target.value)} unit="Rp" value={draft.coverPricePerRim} /><CalculatorField label="Isi per rim" onChange={(event) => update('sheetsPerRim', event.target.value)} unit="lembar" value={draft.sheetsPerRim} /><CalculatorField label="Waste produksi" onChange={(event) => update('wastePercent', event.target.value)} unit="%" value={draft.wastePercent} /></div></div>
        </div>
      </section>
      <aside className="space-y-5 xl:sticky xl:top-6 xl:self-start"><section className="rounded-4xl border border-white/80 bg-white p-6 shadow-xl shadow-slate-300/40"><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">Hasil produksi</p><h2 className="mt-1 text-xl font-black tracking-tight text-slate-950">Kebutuhan buku</h2><div className="mt-5 space-y-3"><ValidationSummary result={result} /><WarningList warnings={result.warnings} /></div><div className="mt-5 grid grid-cols-2 gap-3"><ResultMetric accent label="Buku / lembar" value={data.booksPerSheet} /><ResultMetric label="Halaman final" value={data.finalPages} /><ResultMetric label="Isi / buku" suffix="lembar" value={data.contentSheetsPerBook} /><ResultMetric label="Cover / lembar" value={data.coverPerSheet} /><ResultMetric label="Isi total" suffix="lembar" value={data.contentSheetsTotal} /><ResultMetric label="Cover total" suffix="lembar" value={data.coverSheetsTotal} /><ResultMetric label="Total + waste" suffix="lembar" value={data.recommendedOrder} /><ResultMetric label="Lembar / buku" value={data.sheetsPerBook == null ? null : formatDecimal(data.sheetsPerBook)} /><ResultMetric label="Biaya isi" value={data.contentCost == null ? null : formatIdr(data.contentCost)} /><ResultMetric label="Biaya cover" value={data.coverCost == null ? null : formatIdr(data.coverCost)} /><ResultMetric label="Total biaya" value={data.totalCost == null ? null : formatIdr(data.totalCost)} /><ResultMetric label="Biaya / buku" value={data.costPerCopy == null ? null : formatIdr(data.costPerCopy)} /></div><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-xs font-medium leading-5 text-slate-500"><p>Soft cover dihitung sebagai satu bentang depan + punggung + belakang.</p><p className="mt-1">Referensi awal: 100 halaman 80 gsm ≈ 0,8 cm; 200 halaman ≈ 1,5 cm.</p></div></section></aside>
    </div>
  )
}

