import { Scissors } from 'lucide-react'
import { useState } from 'react'
import { PLANO_PRESETS } from '../paperCalculatorDefaults'
import { CalculatorField } from '../components/CalculatorField'
import { CustomSizeControls } from '../components/CustomSizeControls'
import { PresetButtons } from '../components/PresetButtons'
import { ResultMetric } from '../components/ResultMetric'
import { ValidationSummary } from '../components/ValidationSummary'
import { formatDecimal } from '../domain/numbers'
import { PlanoPreview } from '../previews/PlanoPreview'

export function PlanoCalculatorPanel({ draft, onChange, onDeleteSize, onSaveSize, result, sizes }) {
  const [selectedSchemeId, setSelectedSchemeId] = useState(null)
  const update = (field, value) => onChange({ ...draft, [field]: value })
  const recommended = result.data?.schemes?.find((scheme) => scheme.id === result.data.recommendedSchemeId)
  const selected = result.data?.schemes?.find((scheme) => scheme.id === selectedSchemeId) ?? recommended
  const data = selected ?? {}
  return (
    <div className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
      <section className="rounded-4xl border border-white/80 bg-white p-6 shadow-xl shadow-slate-300/40"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Scissors size={20} /></span><div><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">Optimasi bahan</p><h2 className="text-xl font-black tracking-tight text-slate-950">Potong Plano</h2></div></div><div className="mt-6 space-y-6"><PresetButtons label="Ukuran plano" onSelect={(preset) => onChange({ ...draft, planoWidth: preset.width, planoHeight: preset.height })} presets={[...PLANO_PRESETS, ...sizes.filter((size) => size.type === 'plano')]} selectedHeight={draft.planoHeight} selectedWidth={draft.planoWidth} /><div className="grid gap-4 sm:grid-cols-2"><CalculatorField label="Lebar plano" onChange={(event) => update('planoWidth', event.target.value)} unit="cm" value={draft.planoWidth} /><CalculatorField label="Tinggi plano" onChange={(event) => update('planoHeight', event.target.value)} unit="cm" value={draft.planoHeight} /></div><CustomSizeControls currentHeight={draft.planoHeight} currentWidth={draft.planoWidth} onApply={(size) => onChange({ ...draft, planoWidth: String(size.width), planoHeight: String(size.height) })} onDelete={onDeleteSize} onSave={onSaveSize} sizes={sizes} type="plano" /><div className="border-t border-slate-100 pt-6"><h3 className="text-sm font-black text-slate-900">Ukuran potongan utama</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><CalculatorField label="Lebar potongan" onChange={(event) => update('cutWidth', event.target.value)} unit="cm" value={draft.cutWidth} /><CalculatorField label="Tinggi potongan" onChange={(event) => update('cutHeight', event.target.value)} unit="cm" value={draft.cutHeight} /></div></div><label className="flex items-center gap-3 rounded-2xl border border-slate-100 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-700"><input checked={draft.maximizeRemainder} className="h-4 w-4 accent-blue-600" onChange={(event) => update('maximizeRemainder', event.target.checked)} type="checkbox" />Maksimalkan strip sisa dengan potongan diputar</label></div></section>
      <aside className="space-y-5 xl:sticky xl:top-6 xl:self-start"><section className="rounded-4xl border border-white/80 bg-white p-6 shadow-xl shadow-slate-300/40"><p className="text-xs font-black uppercase tracking-[0.2em] text-blue-600">Skema potong</p><h2 className="mt-1 text-xl font-black tracking-tight text-slate-950">Hasil potong</h2><div className="mt-5"><ValidationSummary result={result} /></div><div className="mt-5 grid grid-cols-2 gap-3"><ResultMetric accent label="Hasil / plano" value={data.totalCuts} /><ResultMetric label="Grid utama" value={data.columns == null ? null : `${data.columns} × ${data.rows}`} /><ResultMetric label="Waste" value={data.wastePercent == null ? null : `${formatDecimal(data.wastePercent)}%`} /><ResultMetric label="Area terpakai" suffix="cm²" value={data.usedArea == null ? null : formatDecimal(data.usedArea)} /></div>{result.status === 'ready' ? <div className="mt-5"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-400">Pilih skema</p><div className="mt-2 grid gap-2">{result.data.schemes.map((scheme) => { const active = scheme.id === data.id; return <button aria-pressed={active} className={`flex items-center justify-between rounded-2xl border px-4 py-3 text-left transition ${active ? 'border-blue-600 bg-blue-600 text-white' : scheme.id === result.data.recommendedSchemeId ? 'border-blue-200 bg-blue-50 text-slate-800' : 'border-slate-100 bg-slate-50 text-slate-800'}`} key={scheme.id} onClick={() => setSelectedSchemeId(scheme.id)} type="button"><span className="text-sm font-bold">{scheme.label}{scheme.id === result.data.recommendedSchemeId ? ' · terbaik' : ''}</span><strong className="text-sm">{scheme.totalCuts} potong</strong></button> })}</div></div> : null}</section><PlanoPreview result={result} scheme={selected} /></aside>
    </div>
  )
}
